# Generated by Django 3.2.15 on 2022-09-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='photos/sub_categories'),
        ),
    ]
