# Generated by Django 3.2.15 on 2022-09-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_alter_sub_category_cat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='cat_image',
            new_name='category_image',
        ),
    ]
