# Generated by Django 3.2.15 on 2022-09-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0003_rename_cat_image_sub_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='category_image',
            new_name='sub_category_image',
        ),
    ]
