# Generated by Django 3.2.15 on 2022-09-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0002_alter_sub_category_cat_image'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True)),
                ('photo_main', models.ImageField(null=True, upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_hotproduct', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.sub_category')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
