# Generated by Django 3.2.15 on 2022-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, help_text='SHOULD BE HIGHER THAN THE ORIGINAL PRODUCT PRICE'),
        ),
    ]
