# Generated by Django 3.0.8 on 2022-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20221031_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingimages',
            name='large',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketingimages',
            name='image',
            field=models.ImageField(max_length=255, upload_to='marketing'),
        ),
    ]
