# Generated by Django 3.0.8 on 2022-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20221031_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingimages',
            name='by_category',
            field=models.BooleanField(default=False, help_text='FOR DIFFERENT CATEGORY'),
        ),
        migrations.AlterField(
            model_name='marketingimages',
            name='large',
            field=models.BooleanField(default=False, help_text='ONLY A POSTER WITH A LARGE POSTER'),
        ),
        migrations.AlterField(
            model_name='marketingimages',
            name='new_product',
            field=models.BooleanField(default=False, help_text='ONLY THE POSTER WITH THE NEW PRODUCT'),
        ),
        migrations.AlterField(
            model_name='marketingimages',
            name='on_offer',
            field=models.BooleanField(default=False, help_text='ONLY THE POSTER WITH THE PRODUCT ON OFFER'),
        ),
    ]
