# Generated by Django 3.0.8 on 2022-12-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20221109_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='boosted',
            new_name='color_your_world',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='free_delivery',
            new_name='flash_sales',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='in_store_offers',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_hotproduct',
            new_name='most_viewed',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='on_offer',
            new_name='new_arrival',
        ),
    ]
