# Generated by Django 3.0.8 on 2022-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_socialurls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialurls',
            options={'verbose_name': 'Social Url', 'verbose_name_plural': 'Social Urls'},
        ),
        migrations.AlterField(
            model_name='socialurls',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialurls',
            name='indeed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialurls',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialurls',
            name='tictok',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialurls',
            name='twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialurls',
            name='youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
