# Generated by Django 3.0.8 on 2022-11-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20221111_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialurls',
            old_name='indeed',
            new_name='linkedin',
        ),
    ]
