# Generated by Django 3.2.15 on 2022-10-21 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcenter',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
