# Generated by Django 3.2.15 on 2022-10-21 10:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_helpcenter_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('blog_intro', ckeditor.fields.RichTextField(help_text='GIVE A SHORT DESCRIPTION ABOUT THE BLOG')),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.AlterModelOptions(
            name='helpcenter',
            options={'verbose_name_plural': 'Help Center'},
        ),
    ]
