# Generated by Django 3.0.8 on 2022-11-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221124_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='blog.BlogAuthor'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='author_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
