# Generated by Django 3.0.8 on 2022-12-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221124_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='author_image',
            field=models.ImageField(upload_to='author_image'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='author_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
