# Generated by Django 3.2.15 on 2022-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_intro',
            field=models.TextField(help_text='GIVE A SHORT DESCRIPTION ABOUT THE BLOG'),
        ),
    ]
