# Generated by Django 3.2.15 on 2022-10-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='latest',
        ),
    ]
