# Generated by Django 3.2.15 on 2022-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpost_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_picture',
            field=models.ImageField(blank=True, upload_to='blogauthor'),
        ),
    ]
