# Generated by Django 3.0.8 on 2022-11-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
