# Generated by Django 3.0.8 on 2022-11-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_picture',
            new_name='author_image',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='author_name',
        ),
    ]
