# Generated by Django 3.0.8 on 2022-11-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20221107_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogauthor',
            old_name='body',
            new_name='about_author',
        ),
    ]
