# Generated by Django 3.0.8 on 2022-11-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20221107_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='blog_description',
        ),
    ]
