# Generated by Django 3.2.15 on 2022-12-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221227_1319'),
        ('blog', '0023_blogpost_published'),
    ]

    operations = [
    ]
