# Generated by Django 3.2.15 on 2022-10-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0002_auto_20221007_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaPaymentCallBack',
        ),
    ]
