# Generated by Django 3.2.15 on 2022-10-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpesa_api', '0007_delete_mpesapaymentcallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPaymentCallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_id', models.CharField(max_length=300)),
                ('checkout_id', models.CharField(max_length=300)),
                ('result_code', models.TextField()),
                ('result_desc', models.TextField()),
                ('amount', models.CharField(max_length=300)),
                ('receipt_number', models.TextField()),
                ('phone_number', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mpesa Payment CallBack',
                'verbose_name_plural': 'Mpesa Payments CallBacks',
            },
        ),
    ]
