# Generated by Django 3.0.8 on 2022-10-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0011_mpesapayment_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapayment',
            name='order_number',
        ),
    ]
