# Generated by Django 3.0.8 on 2022-10-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0012_remove_mpesapayment_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
