# Generated by Django 3.2.15 on 2022-10-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='productVariations',
            new_name='product',
        ),
    ]
