# Generated by Django 3.2.15 on 2022-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20221019_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wish List', 'verbose_name_plural': 'Wish Lists'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
