# Generated by Django 3.0.8 on 2022-10-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20221026_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order Product', 'verbose_name_plural': 'Order Products'},
        ),
    ]
