# Generated by Django 3.2.15 on 2023-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20221231_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subcounty',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
