# Generated by Django 3.2.15 on 2023-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_pay_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_on_delivery',
            name='number_no',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
