# Generated by Django 3.2.15 on 2023-01-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_amount_paid_pay_on_delivery_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_on_delivery',
            name='product_name',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
