# Generated by Django 3.2.15 on 2023-01-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_pay_on_delivery_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_on_delivery',
            name='product_name',
            field=models.TextField(default=0, max_length=300),
        ),
    ]
